name:Vercel Production Workflow

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      -name: Install Vercel CLI
        run: npm install -g vercel

      -name: Pull Vercel Environment Variables
        run: vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      -name: Build  Project Artifact
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      -name: Deploy Production Artifact
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        